model_list:
  # OpenAI-compatible model mappings to Claude
  - model_name: gpt-4o
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: "os.environ/ANTHROPIC_API_KEY"
      
  - model_name: gpt-4o-mini
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"
      
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"
      
  # Direct Claude models
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: "os.environ/ANTHROPIC_API_KEY"
      
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"
      
  # OpenAI models (if API key is available)
  - model_name: openai-gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"
      
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: "os.environ/OPENAI_API_KEY"

# LiteLLM Proxy Configuration
general_settings:
  master_key: "sk-1234567890abcdef"  # Change this in production
  database_url: "sqlite:///./litellm.db"
  
litellm_settings:
  drop_params: true
  set_verbose: false
  json_logs: true