- model_name: claude-4 ### RECEIVED MODEL NAME ###
  litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
    model: claude-opus-4-20250514 ### MODEL NAME sent to `litellm.completion()` ###
    api_key: "os.environ/ANTHROPIC_API_KEY" # does os.getenv("ANTHROPIC_API_KEY")